# Jekyll Resume Theme

# Site settings
title: June Cho Resume
email: junecho2020@u.northwestern.edu
# description: 
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: June Hee Cho
job: front end engineer
location: Evanston
languages: HTML, CSS and Javascript
twitter_username: mattcouchman
github_username:  mattcouchman
codepen_username:  mattcouchman
email_address: some@email.com

# Build settings
markdown: kramdown
