# Jekyll Resume Theme

# Site settings
title: June Cho Resume
email: junecho2020@u.northwestern.edu
# description: 
baseurl: ""
url: "http://asmjune20.github.io"
name: June Hee Cho
job: front end engineer
location: Evanston, IL
languages: Python
LinkedIn: https://www.linkedin.com/in/june-cho-89439519b/


# Build settings
markdown: kramdown
